; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gosub Startup
Gui Add, Tab3, x12 y47 w204 h154, General|Hitleap|Vagex|Fluidstack|Honeygain
Gui Tab, Hitleap
Gui Add, CheckBox, vHit_ena x22 y93 w80 h15, Enable
Gui Add, CheckBox, vHit_sta x22 y114 w80 h15, Auto start
Gui Add, CheckBox, vHit_min x22 y135 w80 h15, Minimized
Gui Add, CheckBox, vHit_mov x22 y156 w80 h15, Moved
Gui Add, CheckBox, vHit_hid x22 y175 w80 h15, Hided
Gui Tab, Vagex
Gui Add, GroupBox, x18 y89 w92 h106, Firefox
Gui Add, GroupBox, x115 y88 w92 h106, Vagex
Gui Add, CheckBox, x25 y104 w80 h15, Enable
Gui Add, CheckBox, x25 y122 w80 h15, Auto start
Gui Add, CheckBox, x25 y140 w80 h15, Minimized
Gui Add, CheckBox, x25 y158 w80 h15, Moved
Gui Add, CheckBox, x25 y178 w80 h15, Hided
Gui Add, CheckBox, x121 y104 w80 h15, Enable
Gui Add, CheckBox, x121 y122 w80 h15, Auto start
Gui Add, CheckBox, x121 y140 w80 h15, Minimized
Gui Add, CheckBox, x121 y158 w80 h15, Moved
Gui Add, CheckBox, x121 y178 w80 h15, Hided
Gui Tab

test=hit_ena
GuiControl,, % test , % %test%
GuiControl,, Hit_sta , %Hit_sta%
GuiControl,, Hit_min , %Hit_min%
GuiControl,, Hit_mov , %Hit_mov%
GuiControl,, Hit_hid , %Hit_hid%

Gui Show, w227 h210, Window
Return

GuiEscape:
GuiClose:
	ExitApp
    ; Gui, Submit
Return
^0::Gui, Show
Return

Startup:
vDefault_ini=
(
;pi tools
[hit]`nena=1`nsta=0`nmin=1`nhid=0`nmov=1
[vagex]`nena=0`nsta=0`nmin=1`nhid=0`nmov=1
[fluidstack]`nena=0`nsta=0`nmin=1`nhid=0`nmov=1
[honeygain]`nena=0`nsta=0`nmin=1`nhid=0`nmov=1
[general]
)
IfNotExist, pi.ini
	FileAppend ,% vDefault_ini, pi.ini, UTF-8

IniRead, Hit_ena, pi.ini, hit, ena , notyet
IniRead, Hit_sta, pi.ini, hit, sta , notyet
IniRead, Hit_min, pi.ini, hit, min , notyet
IniRead, Hit_mov, pi.ini, hit, mov , notyet
IniRead, Hit_hid, pi.ini, hit, hid , notyet
Return
